### ISSUE TITLE
Words ending in -sed, -shed, -wed, or -xed have too many syllables.

### ISSUE THREAD

**Issue by ibanner56** [words/syllable#19]
ex:
"based" -> 2
"mixed" -> 2
"banished" -> 3
"shadowed" -> 3

**Comment by wooorm** [comment]
PRs welcome!

**Comment by ibanner56** [comment]
I'll take a look if I have time over the weekend - for now I just added an extra snippet in our own that decrements the result if it has one of those suffixes, but it's not an elegant fix.

**Comment by wooorm** [comment]
Thanks for raising the issue. I’d love a PR here, so if you have time to work on that I’d be super interested in it!

**Comment by ibanner56** [comment]
Sure - it could be as simple as adding the suffixes to EXPRESSION_SINGLE, but I'm curious why it's just those suffixes, where words like "roughed" or "aimed" don't have the same problem.

I'd rather find the root cause than just patch the hole, but I'll dig into it when I get a chance.

**Comment by ibanner56** [comment]
Oh, or even just MONOSYLLABIC_ONE - but s is already in there...

Hmmm......
