### ISSUE TITLE
Return array with the actual syllables?

### ISSUE THREAD

**Issue by jochemstoel** [words/syllable#23]
I am trying to modify your module slightly to get an array with the syllables, not just the amount. Could you point me in the right direction?

**Comment by wooorm** [comment]
What this library does is take a value, and a syllable of one, and increment or decrement the syllables on certain patterns. It doesn’t really detect boundaries.
I think what you’re looking for is called syllable boundary detection, and some searching found [this project in php](https://github.com/vanderlee/phpSyllable).

**Comment by wooorm** [comment]
Closing for now, I feel like this may be a different project.
