### ISSUE TITLE
Snuffleupagus is wrong!

### ISSUE THREAD

**Issue by rickrich** [words/syllable#25]
https://www.howmanysyllables.com/words/snuffleupagus
5

But:
$ syllable Snuffleupagus
4

**Comment by wooorm** [comment]
Nice find haha. We can’t support all words perfectly, that would mean a huge database of cases (also an interesting project, but not here).

I’m sure there’s some other cases that are misclassified as well, especially of fictional characters. So I’m 🤷‍♂️ on ignoring this but also 🤷‍♂️ on accepting a PR to add it to [`problematic.json`](https://github.com/words/syllable/blob/master/problematic.json).
