### ISSUE TITLE
Feature request: syllablize()

### ISSUE THREAD

**Issue by Maxvien** [words/syllable#45]
Hi, Words team,

I appreciate your work. The `syllable` module is super good.

However, I wish to `syllable` have this function for creating readability texts.

```syllablize('beautiful') // output: ['beau', 'ti', 'ful']```

I think it's not too hard to create this function with your algorithm.

Thank you so much!

Best regards,
Vien Dinh.

**Comment by wooorm** [comment]
Thanks!

> I think it's not too hard to create this function with your algorithm.

I kinda think it would be really hard. For one: boundaries don’t always exist. It would be a completely different algorithm, in which case having it as a different project might make more sense to me!
