### ISSUE TITLE
ERR_REQUIRE_ESM: Must use import (I am using import)

### ISSUE THREAD

**Issue by thewebguy** [words/syllable#52]
Getting this:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/syllable/index.js from extendToMinimumLength.ts not supported.
Instead change the require of index.js in extendToMinimumLength.ts to a dynamic import() which is available in all CommonJS modules.
```

But I am using import?

**Comment by wooorm** [comment]
You may be using an `import x from 'y'` statement, but you are not using actual ESM.
You likely have a build step, that transforms some code, but doesn’t transform other code.

Switch to actual ESM to use this package or downgrade if you’re not ready for actual ESM yet.
